function precios(){
	
	var dataSet = [
    ["Pastel de Queso con Zarzamora","grande","365","213","234","434"],
	["Pastel de Queso con Zarzamora","mini","365","213","234","434"],
	["Pastel de Queso con Durazno","365","213","234","434"],
	["Pastel de Queso con Queso","365","213","234","434"],
	["Pastel de Queso con Chocolate","365","213","234","434"]
];

var dataprecios=[
	
	["Perro","Pro plan","Húmedo","Normal","Cachorro","PUPPY","NA","Lata","0.368","49.1","83","0","-"],
	["Perro","Pro plan","Húmedo","Normal","Cachorro","PUPPY","NA","Pouch","0.085","12.9","21","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Pequeña","Bulto","1","196.4","299","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Pequeña","Bulto","3.5","513.9","799","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Pequeña","Bulto","7.5","954","1440","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Mediana","Bulto","3","474.8","709","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Mediana","Bulto","7.5","1017.8","1530","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Mediana","Bulto","13","1510.3","2169","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Grande","Bulto","3.5","480.8","745","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","PUPPY","Grande","Bulto","13","1397.9","2060","0","-"],
	["Perro","Pro plan","Húmedo","Normal","Adulto","ADULT","NA","Lata","0.368","49.1","83","0","-"],
	["Perro","Pro plan","Húmedo","Normal","Adulto","ADULT","NA","Pouch","0.085","12.9","21","0","-"],
	["Perro","Pro plan","Húmedo","Normal","Adulto","ADULT","NA","Pouch","0.085","12.9","21","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Pequeña","Bulto","1","187.4","285","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Pequeña","Bulto","3.5","486.2","770","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Pequeña","Bulto","7.5","906.1","1365","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Mediana","Bulto","3","452.8","675","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Mediana","Bulto","7.5","926.3","1395","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Mediana","Bulto","13","1301","1979","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Grande","Bulto","3","424.9","629","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","ADULT","Grande","Bulto","13","1221","1835","0","-"],
	["Perro","Pro plan","Húmedo","Normal","Senior","ACTIVE MIND","NA","Lata","0.368","49.1","83","0","-"],
	["Perro","Pro plan","Húmedo","Normal","Senior","ACTIVE MIND","NA","Pouch","0.085","12.9","21","0","-"],
	["Perro","Pro plan","Seco","Normal","Senior","ACTIVE MIND","Pequeña","Bulto","1","190","290","0","-"],
	["Perro","Pro plan","Seco","Normal","Senior","ACTIVE MIND","Pequeña","Bulto","3","442.3","670","0","-"],
	["Perro","Pro plan","Seco","Normal","Senior","ACTIVE MIND","Pequeña","Bulto","7.5","1003.9","1500","0","-"],
	["Perro","Pro plan","Seco","Normal","Senior","ACTIVE MIND","Mediana","Bulto","3","450.1","679","0","-"],
	["Perro","Pro plan","Seco","Normal","Senior","ACTIVE MIND","Mediana","Bulto","7.5","984","1479","0","-"],
	["Perro","Pro plan","Seco","Normal","Senior","ACTIVE MIND","Mediana","Bulto","13","1273","1990","0","-"],
	["Perro","Pro plan","Húmedo","Normal","Adulto","SESITIVE SKIN","NA","Lata","0.368","49.1","83","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","SESITIVE SKIN","NA","Bulto","3","482.3","729","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","SESITIVE SKIN","NA","Bulto","13","1564.8","2330","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","SESITIVE SKIN","Pequeña","Bulto","1","197.5","299","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","SESITIVE SKIN","Pequeña","Bulto","3","446.9","679","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","SESITIVE SKIN","Pequeña","Bulto","7.5","988.4","1490","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","SESITIVE SKIN","Mediana","Bulto","3","438.3","640","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","SESITIVE SKIN","Mediana","Bulto","13","1560.9","2244","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","SENSITIVE DIGESTION","NA","Bulto","3.5","550.4","850","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","SENSITIVE DIGESTION","NA","Bulto","10","1413.7","2190","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","REDUCED CALORIES","NA","Bulto","3","450","680","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","REDUCED CALORIES","NA","Bulto","13","1437.6","2170","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXIGENT","NA","Bulto","1","210.6","305","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXIGENT","NA","Bulto","3","498.6","749","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXIGENT","NA","Bulto","7.5","1139","1695","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","DELICATE STRUCTURE","NA","Bulto","3","509.6","749","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","PERFORMANCE","NA","Bulto","13","1466.3","2190","0","-"],
	["Perro","Pro plan","Húmedo","Dieta Veterinaria (VD)","NA","OM - Overweight Management","NA","Lata","0.377","55.4","78.5","0","om-lata"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","OM - Overweight Management","NA","Bulto","2.72","389.9","589","0","om"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","OM - Overweight Management","NA","Bulto","8.16","1074","1415","0","om"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","OM - Overweight Management","NA","Bulto","14.5","1821.2","2460","0","om"],
	["Perro","Pro plan","Húmedo","Dieta Veterinaria (VD)","NA","HA - Hydrolized","NA","Lata","0.377","58.9","82","0","ha-lata"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","HA - Hydrolized","NA","Bulto","2.72","557.7","749","0","ha"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","HA - Hydrolized","NA","Bulto","7.48","1166.6","1575","0","ha"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","HA - Hydrolized","NA","Bulto","11.34","1811.9","2450","0","ha"],
	["Perro","Pro plan","Húmedo","Dieta Veterinaria (VD)","NA","NF - Kidney Function","NA","Lata","0.377","52.7","78.5","0","nf-lata"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","NF - Kidney Function","NA","Bulto","2.72","438.7","589","0","nf"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","NF - Kidney Function","NA","Bulto","8.16","1032.3","1380","0","nf"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","NF - Kidney Function","NA","Bulto","15.4","1917.5","2590","0","nf"],
	["Perro","Pro plan","Húmedo","Dieta Veterinaria (VD)","NA","EN - Gastroenteric","NA","Lata","0.377","52.7","78.5","0","en-lata"],
	["Perro","Pro plan","Húmedo","Dieta Veterinaria (VD)","NA","EN - Gastroenteric Low Fat","NA","Lata","0.377","55.4","78.5","0","en-lata-low-fat"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","EN - Gastroenteric","NA","Bulto","2.72","420.3","609","0","en"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","EN - Gastroenteric","NA","Bulto","8.16","1001.5","1325","0","en"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","EN - Gastroenteric","NA","Bulto","14.5","1801.5","2435","0","en"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","EN - Gastroenteric Low Fat","NA","Bulto","2.72","443.6","580","0","en-low-fat"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","EN - Gastroenteric Low Fat","NA","Bulto","14.5","1784.1","2410","0","en-low-fat"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","EN - Gastroenteric Fiber Balance","NA","Bulto","2.72","467.3","615","0","en-fiber"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","EN - Gastroenteric Fiber Balance","NA","Bulto","14.5","1885","2550","0","en-fiber"],
	["Perro","Pro plan","Húmedo","Dieta Veterinaria (VD)","NA","UR - Urinary","NA","Lata","0.377","55.4","78.5","0","ur-lata"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","UR - Urinary","NA","Bulto","2.72","432.6","579","0","ur"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","UR - Urinary","NA","Bulto","7.48","985.7","1290","0","ur"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","UR - Urinary","NA","Bulto","11.3","1459.3","1972","0","ur"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","NC - Neurocare","NA","Bulto","2.72","518","689","0","nc"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","NC - Neurocare","NA","Bulto","4.9","895.7","1175","0","nc"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","NC - Neurocare","NA","Bulto","11.3","1954","2649","0","nc"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","DH - Dental Health","NA","Bulto","2.72","504","670","0","dh"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","DRM- Dermatologic Management Naturals","NA","Bulto","2.72","439.2","590","0","drm"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","DRM- Dermatologic Management Naturals","NA","Bulto","7.48","1077.6","1455","0","drm"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","JM - Joint Mobility","NA","Bulto","2.72","515","690","0","jm"],
	["Perro","Pro plan","Seco","Dieta Veterinaria (VD)","NA","JM - Joint Mobility","NA","Bulto","8.16","1136.5","1535","0","jm"],
	["Perro / Gato","Pro plan","Húmedo","Dieta Veterinaria (VD)","NA","CN - Convalescence","NA","Lata","0.155","41.6","68.5","0","cn"],
	["Perro","Pro plan","-","Dieta Veterinaria (VD)","NA","PROBIÓTICOS - Fortiflora Canine","NA","NA","0.0301","326.9","495","0","fortiflora-canino"],
	["Perro","Pro plan","-","Dieta Veterinaria (VD)","NA","PROBIÓTICOS - Calming Care Canine","NA","NA","0.045","437.31","680","0","calming-canino"],
	["Perro","Pro plan","-","Dieta Veterinaria (VD)","NA","Snack Gentle Snacker","NA","NA","0.227","112","207","0","snack"],
	["Perro","Pro plan","-","Dieta Veterinaria (VD)","NA","Lite Snacker","NA","NA","0.68","170.8","317.2","0","lite-snack"],
	["Perro","Pro plan","Seco","Normal","Cachorro","EXCELLENT","Pequeña","Bulto","3.5","321.5","499","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","EXCELLENT","Pequeña","Bulto","7.5","619.2","959","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","EXCELLENT COMPLETE","NA","Bulto","4","283.3","439","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","EXCELLENT COMPLETE","NA","Bulto","15","956.4","1479","0","-"],
	["Perro","Pro plan","Seco","Normal","Cachorro","EXCELLENT COMPLETE","NA","Bulto","20","1249.7","1939","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXCELLENT","Pequeña","Bulto","3.5","283.5","439","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXCELLENT","Pequeña","Bulto","7.5","532.1","825","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXCELLENT COMPLETE","NA","Bulto","4","261.6","405","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXCELLENT COMPLETE","NA","Bulto","15","825.6","1275","0","-"],
	["Perro","Pro plan","Seco","Normal","Adulto","EXCELLENT COMPLETE","NA","Bulto","20","1050.7","1630","0","-"],
	["Perro","Pro plan","Seco","Normal","NA","CORDERO","NA","Bulto","20.4","1366.4","2252","0","-"],
	["Gato","Pro plan","-","Dieta Veterinaria (VD)","NA","PROBIÓTICOS - Fortiflora Feline","NA","NA","0.0301","326.9","495","0","fortiflora-felino"],
	["Gato","Pro plan","Húmedo","Normal","Gatito","Kitten","NA","Lata","0.085","20.9","38","0","-"],
	["Gato","Pro plan","Húmedo","Normal","Gatito","Kitten","NA","Pouch","0.085","13","21","0","-"],
	["Gato","Pro plan","Seco","Normal","Gatito","Kitten","NA","Bulto","1.5","299.6","415","0","-"],
	["Gato","Pro plan","Seco","Normal","Gatito","Kitten","NA","Bulto","3","535.8","750","0","-"],
	["Gato","Pro plan","Húmedo","Normal","Gato","Adult","NA","Lata","0.085","20.9","38","0","-"],
	["Gato","Pro plan","Húmedo","Normal","Gato","Adult","NA","Pouch","0.085","13","21","0","-"],
	["Gato","Pro plan","Húmedo","Normal","Gato","Adult","NA","Pouch","0.085","13","21","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Adult","NA","Bulto","3","514.7","702","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Adult","NA","Bulto","7.5","1070.5","1475","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Senior","NA","Bulto","3","489","749","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Sensitive","NA","Bulto","3","495.2","755","0","-"],
	["Gato","Pro plan","Húmedo","Normal","Gato","Reduced calorie","NA","Lata","0.085","20.9","38","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Reduced calorie","NA","Bulto","3","502.8","785","0","-"],
	["Gato","Pro plan","Húmedo","Normal","Gato","Urinary","NA","Lata","0.085","13","21","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Urinary","NA","Bulto","3","558.1","739","0","-"],
	["Gato","Pro plan","Húmedo","Normal","Gato","Sterilized","NA","Pouch","0.085","13","21","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Sterilized","NA","Bulto","3","489","755","0","-"],
	["Gato","Pro plan","Seco","Normal","Gato","Sterilized","NA","Bulto","7.5","1030","1590","0","-"],
	["Gato","Pro plan","Húmedo","Dieta Veterinaria (VD)","Feline","Sobrepeso y obesidad OM Feline","NA","Lata","0.156","52.1","70","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Sobrepeso y obesidad OM Feline","NA","Bulto","2.72","532.4","715","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Sobrepeso y obesidad OM Feline","NA","Bulto","7.36","1281.8","1735","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Alergia alimentaria / Trastornos gastrointestinales HA Feline","NA","Bulto","1.81","485","660","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Alergia alimentaria / Trastornos gastrointestinales HA Feline","NA","Bulto","3.63","879.28","1190","0","-"],
	["Gato","Pro plan","Húmedo","Dieta Veterinaria (VD)","Feline","Enfermedad renal temprana y avanzada NF Early care feline","NA","Lata","0.156","52.1","70","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Enfermedad renal temprana y avanzada NF Early care feline","NA","Bulto","3.63","570.3","779","0","-"],
	["Gato","Pro plan","Húmedo","Dieta Veterinaria (VD)","Feline","Enfermedad renal temprana y avanzada NF Advanced care feline","NA","Lata","0.156","52.1","70","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Enfermedad renal temprana y avanzada NF Advanced care feline","NA","Bulto","3.63","581.7","790","0","-"],
	["Gato","Pro plan","Húmedo","Dieta Veterinaria (VD)","Feline","Padecimientos gastrointestinales EN Feline","NA","Lata","0.156","52.1","70","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Padecimientos gastrointestinales EN Feline","NA","Bulto","2.72","582.8","735","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Padecimientos gastrointestinales EN Feline","NA","Bulto","4.53","817.8","1105","0","-"],
	["Gato","Pro plan","Húmedo","Dieta Veterinaria (VD)","Feline","Trastornos urinarios estruvita / Feline UR","NA","Lata","0.156","52.1","70","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Trastornos urinarios estruvita / Feline UR","NA","Bulto","2.72","545.2","739","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Salud dental / DH Feline","NA","Bulto","2.72","628.3","845","0","-"],
	["Gato","Pro plan","Húmedo","Dieta Veterinaria (VD)","Feline","Diabéticos / DM Feline","NA","Lata","0.156","52.1","70","0","-"],
	["Gato","Pro plan","Seco","Dieta Veterinaria (VD)","Feline","Diabéticos / DM Feline","NA","Bulto","2.72","593.7","795","0","-"],
	["Gato y perro","Pro plan","Húmedo","Dieta Veterinaria (VD)","Feline","Desnutrición convalescencia / CN Canine / Feline","NA","Lata","0.155","41.6","68.5","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nupec","NA","Bulto","2","168","247","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nupec","NA","Bulto","5","371","546","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nupec","NA","Bulto","8","590","825","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nupec","NA","Bulto","15","1062","1487","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nupec","NA","Bulto","20","1398","1957","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nupec","NA","Bulto","2","145","214","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nupec","NA","Bulto","5","342","503","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nupec","NA","Bulto","8","552","772","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nupec","NA","Bulto","15","915","1281","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nupec","NA","Bulto","20","1160","1625","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nupec","Raza pequeña","Bulto","2","193","298","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nupec","Raza pequeña","Bulto","8","695","1018","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nupec","Raza pequeña","Bulto","2","168","259","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nupec","Raza pequeña","Bulto","8","600","883","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nupec","Adult Indoor","Bulto","1.5","137","201","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nupec","Adult Indoor","Bulto","3","264","394","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nupec","Adult Indoor","Bulto","5","446","634","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nupec","Felino Kitten","Bulto","1.5","152","222","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nupec","Felino Kitten","Bulto","3","297","443","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nupec","Felino Hairball","Bulto","1.5","145","212","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nupec","Felino Hairball","Bulto","3","283","422","0","-"],
	["Gato","Nupec","Seco","Normal","Senior","Nupec","Felino Senior","","1.5","155","227","0","-"],
	["Gato","Nupec","Seco","Normal","Senior","Nupec","Felino Senior","","3","304","453","0","-"],
	["Perro","Nupec","Treats","Normal","NA","Nupec","NA","Bolsa","180","50","80","0","-"],
	["Perro","Nupec","Treats","Normal","NA","Nupec","NA","Bolsa","180","50","80","0","-"],
	["Perro","Nupec","Treats","Normal","NA","Nupec","NA","Bolsa","180","50","80","0","-"],
	["Perro","Nupec","Treats","Normal","NA","Nupec","NA","Bolsa","180","50","80","0","-"],
	["Perro","Nupec","Treats","Normal","NA","Nupec","NA","Bolsa","180","50","80","0","-"],
	["Perro","Nupec","Treats","Normal","NA","Nupec","NA","Bolsa","180","50","80","0","-"],
	["Perro","Nupec","Húmedo","Normal","Adulto","Nupec","NA","Paquete","x4","68","100","0","-"],
	["Perro","Nupec","Húmedo","Normal","Adulto","Nupec","NA","Paquete","x4","64","100","0","-"],
	["Perro","Nupec","Húmedo","Normal","Cachorro","Nupec","NA","Paquete","x4","64","100","0","-"],
	["Perro","Nupec","Húmedo","Normal","Adulto","Nupec","NA","Paquete","x4","68","100","0","-"],
	["Gato","Nupec","Húmedo","Normal","Adulto","Nupec","NA","Paquete","x4","64","100","0","-"],
	["Gato","Nupec","Húmedo","Normal","Adulto","Nupec","NA","Paquete","x4","68","100","0","-"],
	["Gato","Nupec","Húmedo","Normal","Adulto","Nupec","NA","Paquete","x4","64","100","0","-"],
	["Gato","Nupec","Húmedo","Normal","Adulto","Nupec","NA","Paquete","x4","68","100","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Optimo","NA","Bulto","2","86","100","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Optimo","NA","Bulto","4","165","192","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Optimo","NA","Bulto","20","698","868","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Optimo","NA","Bulto","2","78","95","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Optimo","NA","Bulto","4","148","181","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Optimo","NA","Bulto","20","789","1014","0","-"],
	["Perro","Nupec","Treats","Normal","Adulto","Optimo","NA","Bolsa","0.8","21","26","0","-"],
	["Perro","Nupec","Treats","Normal","Adulto","Optimo","NA","Bolsa","0.6","17","22","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Felino","NA","Bulto","1.5","79","88","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Felino","NA","Bulto","3","136","157","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Felino","NA","Bulto","20","772","943","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nufit","NA","Bulto","2","128","157","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nufit","NA","Bulto","4","238","293","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nufit","NA","Bulto","8","412","507","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nufit","NA","Bulto","20","927","1104","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nufit","NA","Bulto","2","121","150","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nufit","NA","Bulto","4","221","272","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nufit","NA","Bulto","8","391","481","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nufit","NA","Bulto","15","684","821","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nufit","NA","Bulto","20","1087","1304","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nucan","NA","Bulto","0.9","26","32","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nucan","NA","Bulto","1.8","51","63","0","-"],
	["Perro","Nupec","Seco","Normal","Adulto","Nucan","NA","Bulto","25","660","828","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nucan","NA","Bulto","0.9","31","36","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nucan","NA","Bulto","1.8","60","71","0","-"],
	["Perro","Nupec","Seco","Normal","Cachorro","Nucan","NA","Bulto","20","618","761","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nucat","NA","Bulto","0.9","32","41","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nucat","NA","Bulto","1.8","63","78","0","-"],
	["Gato","Nupec","Seco","Normal","Adulto","Nucat","NA","Bulto","15","479","601","0","-"]	

];

return dataprecios;
}